import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class StockRecords(models.Model):
    NIFTY_BETA_STOCKS = [('OTHER', 'OTHER'),
                         ("3M India Ltd.", "3M India Ltd."),
                         ("ABB India Ltd.", "ABB India Ltd."),
                         ("ABB Power Products and Systems India Ltd.", "ABB Power Products and Systems India Ltd."),
                         ("ACC Ltd.", "ACC Ltd."),
                         ("AIA Engineering Ltd.", "AIA Engineering Ltd."),
                         ("APL Apollo Tubes Ltd.", "APL Apollo Tubes Ltd."),
                         ("AU Small Finance Bank Ltd.", "AU Small Finance Bank Ltd."),
                         ("Aarti Drugs Ltd.", "Aarti Drugs Ltd."),
                         ("Aarti Industries Ltd.", "Aarti Industries Ltd."),
                         ("Aavas Financiers Ltd.", "Aavas Financiers Ltd."),
                         ("Abbott India Ltd.", "Abbott India Ltd."),
                         ("Adani Enterprises Ltd.", "Adani Enterprises Ltd."),
                         ("Adani Green Energy Ltd.", "Adani Green Energy Ltd."),
                         ("Adani Ports and Special Economic Zone Ltd.", "Adani Ports and Special Economic Zone Ltd."),
                         ("Adani Total Gas Ltd.", "Adani Total Gas Ltd."),
                         ("Adani Transmission Ltd.", "Adani Transmission Ltd."),
                         ("Aditya Birla Capital Ltd.", "Aditya Birla Capital Ltd."),
                         ("Aditya Birla Fashion and Retail Ltd.", "Aditya Birla Fashion and Retail Ltd."),
                         ("Advanced Enzyme Tech Ltd.", "Advanced Enzyme Tech Ltd."),
                         ("Aegis Logistics Ltd.", "Aegis Logistics Ltd."),
                         ("Affle (India) Ltd.", "Affle (India) Ltd."),
                         ("Ajanta Pharmaceuticals Ltd.", "Ajanta Pharmaceuticals Ltd."),
                         ("Akzo Nobel India Ltd.", "Akzo Nobel India Ltd."),
                         ("Alembic Ltd.", "Alembic Ltd."),
                         ("Alembic Pharmaceuticals Ltd.", "Alembic Pharmaceuticals Ltd."),
                         ("Alkem Laboratories Ltd.", "Alkem Laboratories Ltd."),
                         ("Alkyl Amines Chemicals Ltd.", "Alkyl Amines Chemicals Ltd."),
                         ("Alok Industries Ltd.", "Alok Industries Ltd."),
                         ("Amara Raja Batteries Ltd.", "Amara Raja Batteries Ltd."),
                         ("Amber Enterprises India Ltd.", "Amber Enterprises India Ltd."),
                         ("Ambuja Cements Ltd.", "Ambuja Cements Ltd."),
                         ("Angel Broking Ltd.", "Angel Broking Ltd."),
                         ("Apollo Hospitals Enterprise Ltd.", "Apollo Hospitals Enterprise Ltd."),
                         ("Apollo Tyres Ltd.", "Apollo Tyres Ltd."),
                         ("Asahi India Glass Ltd.", "Asahi India Glass Ltd."),
                         ("Ashok Leyland Ltd.", "Ashok Leyland Ltd."),
                         ("Ashoka Buildcon Ltd.", "Ashoka Buildcon Ltd."),
                         ("Asian Paints Ltd.", "Asian Paints Ltd."),
                         ("Aster DM Healthcare Ltd.", "Aster DM Healthcare Ltd."),
                         ("AstraZenca Pharma India Ltd.", "AstraZenca Pharma India Ltd."),
                         ("Astral Ltd.", "Astral Ltd."),
                         ("Atul Ltd.", "Atul Ltd."),
                         ("Aurobindo Pharma Ltd.", "Aurobindo Pharma Ltd."),
                         ("Avanti Feeds Ltd.", "Avanti Feeds Ltd."),
                         ("Avenue Supermarts Ltd.", "Avenue Supermarts Ltd."),
                         ("Axis Bank Ltd.", "Axis Bank Ltd."),
                         ("BASF India Ltd.", "BASF India Ltd."),
                         ("BEML Ltd.", "BEML Ltd."),
                         ("BSE Ltd.", "BSE Ltd."),
                         ("Bajaj Auto Ltd.", "Bajaj Auto Ltd."),
                         ("Bajaj Consumer Care Ltd.", "Bajaj Consumer Care Ltd."),
                         ("Bajaj Electricals Ltd", "Bajaj Electricals Ltd"),
                         ("Bajaj Finance Ltd.", "Bajaj Finance Ltd."),
                         ("Bajaj Finserv Ltd.", "Bajaj Finserv Ltd."),
                         ("Bajaj Holdings & Investment Ltd.", "Bajaj Holdings & Investment Ltd."),
                         ("Balaji Amines Ltd.", "Balaji Amines Ltd."),
                         ("Balkrishna Industries Ltd.", "Balkrishna Industries Ltd."),
                         ("Balmer Lawrie & Co. Ltd.", "Balmer Lawrie & Co. Ltd."),
                         ("Balrampur Chini Mills Ltd.", "Balrampur Chini Mills Ltd."),
                         ("Bandhan Bank Ltd.", "Bandhan Bank Ltd."),
                         ("Bank of Baroda", "Bank of Baroda"),
                         ("Bank of India", "Bank of India"),
                         ("Bank of Maharashtra.", "Bank of Maharashtra."),
                         ("Bata India Ltd.", "Bata India Ltd."),
                         ("Bayer Cropscience Ltd.", "Bayer Cropscience Ltd."),
                         ("Berger Paints India Ltd.", "Berger Paints India Ltd."),
                         ("Bharat Dynamics Ltd.", "Bharat Dynamics Ltd."),
                         ("Bharat Electronics Ltd.", "Bharat Electronics Ltd."),
                         ("Bharat Forge Ltd.", "Bharat Forge Ltd."),
                         ("Bharat Heavy Electricals Ltd.", "Bharat Heavy Electricals Ltd."),
                         ("Bharat Petroleum Corporation Ltd.", "Bharat Petroleum Corporation Ltd."),
                         ("Bharat Rasayan Ltd.", "Bharat Rasayan Ltd."),
                         ("Bharti Airtel Ltd.", "Bharti Airtel Ltd."),
                         ("Biocon Ltd.", "Biocon Ltd."),
                         ("Birla Corporation Ltd.", "Birla Corporation Ltd."),
                         ("Birlasoft Ltd.", "Birlasoft Ltd."),
                         ("Bliss GVS Pharma Ltd.", "Bliss GVS Pharma Ltd."),
                         ("Blue Dart Express Ltd.", "Blue Dart Express Ltd."),
                         ("Blue Star Ltd.", "Blue Star Ltd."),
                         ("Bombay Burmah Trading Corporation Ltd.", "Bombay Burmah Trading Corporation Ltd."),
                         ("Bosch Ltd.", "Bosch Ltd."),
                         ("Brigade Enterprises Ltd.", "Brigade Enterprises Ltd."),
                         ("Britannia Industries Ltd.", "Britannia Industries Ltd."),
                         ("Burger King India Ltd.", "Burger King India Ltd."),
                         ("CCL Products (I) Ltd.", "CCL Products (I) Ltd."),
                         ("CESC Ltd.", "CESC Ltd."),
                         ("CRISIL Ltd.", "CRISIL Ltd."),
                         ("CSB Bank Ltd.", "CSB Bank Ltd."),
                         ("Cadila Healthcare Ltd.", "Cadila Healthcare Ltd."),
                         ("Can Fin Homes Ltd.", "Can Fin Homes Ltd."),
                         ("Canara Bank", "Canara Bank"),
                         ("Caplin Point Laboratories Ltd.", "Caplin Point Laboratories Ltd."),
                         ("Capri Global Capital Ltd.", "Capri Global Capital Ltd."),
                         ("Carborundum Universal Ltd.", "Carborundum Universal Ltd."),
                         ("Castrol India Ltd.", "Castrol India Ltd."),
                         ("Ceat Ltd.", "Ceat Ltd."),
                         ("Central Bank of India", "Central Bank of India"),
                         ("Central Depository Services (India) Ltd.", "Central Depository Services (India) Ltd."),
                         ("Century Plyboards (India) Ltd.", "Century Plyboards (India) Ltd."),
                         ("Century Textile & Industries Ltd.", "Century Textile & Industries Ltd."),
                         ("Cera Sanitaryware Ltd", "Cera Sanitaryware Ltd"),
                         ("Chalet Hotels Ltd.", "Chalet Hotels Ltd."),
                         ("Chambal Fertilizers & Chemicals Ltd.", "Chambal Fertilizers & Chemicals Ltd."),
                         ("Cholamandalam Financial Holdings Ltd.", "Cholamandalam Financial Holdings Ltd."),
                         ("Cholamandalam Investment and Finance Company Ltd.",
                          "Cholamandalam Investment and Finance Company Ltd."),
                         ("Cipla Ltd.", "Cipla Ltd."),
                         ("City Union Bank Ltd.", "City Union Bank Ltd."),
                         ("Coal India Ltd.", "Coal India Ltd."),
                         ("Cochin Shipyard Ltd.", "Cochin Shipyard Ltd."),
                         ("Coforge Ltd.", "Coforge Ltd."),
                         ("Colgate Palmolive (India) Ltd.", "Colgate Palmolive (India) Ltd."),
                         ("Computer Age Management Services Ltd.", "Computer Age Management Services Ltd."),
                         ("Container Corporation of India Ltd.", "Container Corporation of India Ltd."),
                         ("Coromandel International Ltd.", "Coromandel International Ltd."),
                         ("CreditAccess Grameen Ltd.", "CreditAccess Grameen Ltd."),
                         ("Crompton Greaves Consumer Electricals Ltd.", "Crompton Greaves Consumer Electricals Ltd."),
                         ("Cummins India Ltd.", "Cummins India Ltd."),
                         ("Cyient Ltd.", "Cyient Ltd."),
                         ("DCB Bank Ltd.", "DCB Bank Ltd."),
                         ("DCM Shriram Ltd.", "DCM Shriram Ltd."),
                         ("DLF Ltd.", "DLF Ltd."),
                         ("Dabur India Ltd.", "Dabur India Ltd."),
                         ("Dalmia Bharat Ltd.", "Dalmia Bharat Ltd."),
                         ("Deepak Nitrite Ltd.", "Deepak Nitrite Ltd."),
                         ("Delta Corp Ltd.", "Delta Corp Ltd."),
                         ("Dhani Services Ltd.", "Dhani Services Ltd."),
                         ("Dhanuka Agritech Ltd.", "Dhanuka Agritech Ltd."),
                         ("Dilip Buildcon Ltd.", "Dilip Buildcon Ltd."),
                         ("Dish TV India Ltd.", "Dish TV India Ltd."),
                         ("Dishman Carbogen Amcis Ltd.", "Dishman Carbogen Amcis Ltd."),
                         ("Divi's Laboratories Ltd.", "Divi's Laboratories Ltd."),
                         ("Dixon Technologies (India) Ltd.", "Dixon Technologies (India) Ltd."),
                         ("Dr. Lal Path Labs Ltd.", "Dr. Lal Path Labs Ltd."),
                         ("Dr. Reddy's Laboratories Ltd.", "Dr. Reddy's Laboratories Ltd."),
                         ("E.I.D. Parry (India) Ltd.", "E.I.D. Parry (India) Ltd."),
                         ("EIH Ltd.", "EIH Ltd."),
                         ("EPL Ltd.", "EPL Ltd."),
                         ("Edelweiss Financial Services Ltd.", "Edelweiss Financial Services Ltd."),
                         ("Eicher Motors Ltd.", "Eicher Motors Ltd."),
                         ("Elgi Equipments Ltd.", "Elgi Equipments Ltd."),
                         ("Emami Ltd.", "Emami Ltd."),
                         ("Endurance Technologies Ltd.", "Endurance Technologies Ltd."),
                         ("Engineers India Ltd.", "Engineers India Ltd."),
                         ("Equitas Holdings Ltd.", "Equitas Holdings Ltd."),
                         ("Eris Lifesciences Ltd.", "Eris Lifesciences Ltd."),
                         ("Escorts Ltd.", "Escorts Ltd."),
                         ("Exide Industries Ltd.", "Exide Industries Ltd."),
                         ("FDC Ltd.", "FDC Ltd."),
                         ("Federal Bank Ltd.", "Federal Bank Ltd."),
                         ("Fine Organic Industries Ltd.", "Fine Organic Industries Ltd."),
                         ("Finolex Cables Ltd.", "Finolex Cables Ltd."),
                         ("Finolex Industries Ltd.", "Finolex Industries Ltd."),
                         ("Firstsource Solutions Ltd.", "Firstsource Solutions Ltd."),
                         ("Fortis Healthcare Ltd.", "Fortis Healthcare Ltd."),
                         ("Future Consumer Ltd.", "Future Consumer Ltd."),
                         ("Future Retail Ltd.", "Future Retail Ltd."),
                         ("GAIL (India) Ltd.", "GAIL (India) Ltd."),
                         ("GE Power India Ltd.", "GE Power India Ltd."),
                         ("GMM Pfaudler Ltd.", "GMM Pfaudler Ltd."),
                         ("GMR Infrastructure Ltd.", "GMR Infrastructure Ltd."),
                         ("Galaxy Surfactants Ltd.", "Galaxy Surfactants Ltd."),
                         ("Garden Reach Shipbuilders & Engineers Ltd.", "Garden Reach Shipbuilders & Engineers Ltd."),
                         ("Garware Technical Fibres Ltd.", "Garware Technical Fibres Ltd."),
                         ("General Insurance Corporation of India", "General Insurance Corporation of India"),
                         ("Gillette India Ltd.", "Gillette India Ltd."),
                         ("Glaxosmithkline Pharmaceuticals Ltd.", "Glaxosmithkline Pharmaceuticals Ltd."),
                         ("Glenmark Pharmaceuticals Ltd.", "Glenmark Pharmaceuticals Ltd."),
                         ("Godfrey Phillips India Ltd.", "Godfrey Phillips India Ltd."),
                         ("Godrej Agrovet Ltd.", "Godrej Agrovet Ltd."),
                         ("Godrej Consumer Products Ltd.", "Godrej Consumer Products Ltd."),
                         ("Godrej Industries Ltd.", "Godrej Industries Ltd."),
                         ("Godrej Properties Ltd.", "Godrej Properties Ltd."),
                         ("Granules India Ltd.", "Granules India Ltd."),
                         ("Graphite India Ltd.", "Graphite India Ltd."),
                         ("Grasim Industries Ltd.", "Grasim Industries Ltd."),
                         ("Great Eastern Shipping Co. Ltd.", "Great Eastern Shipping Co. Ltd."),
                         ("Greaves Cotton Ltd.", "Greaves Cotton Ltd."),
                         ("Grindwell Norton Ltd.", "Grindwell Norton Ltd."),
                         ("Gujarat Alkalies & Chemicals Ltd.", "Gujarat Alkalies & Chemicals Ltd."),
                         ("Gujarat Ambuja Exports Ltd.", "Gujarat Ambuja Exports Ltd."),
                         ("Gujarat Fluorochemicals Ltd.", "Gujarat Fluorochemicals Ltd."),
                         ("Gujarat Gas Ltd.", "Gujarat Gas Ltd."),
                         ("Gujarat Narmada Valley Fertilizers and Chemicals Ltd.",
                          "Gujarat Narmada Valley Fertilizers and Chemicals Ltd."),
                         ("Gujarat Pipavav Port Ltd.", "Gujarat Pipavav Port Ltd."),
                         ("Gujarat State Fertilizers & Chemicals Ltd.", "Gujarat State Fertilizers & Chemicals Ltd."),
                         ("Gujarat State Petronet Ltd.", "Gujarat State Petronet Ltd."),
                         ("Gulf Oil Lubricants India Ltd.", "Gulf Oil Lubricants India Ltd."),
                         ("H.E.G. Ltd.", "H.E.G. Ltd."),
                         ("HCL Technologies Ltd.", "HCL Technologies Ltd."),
                         ("HDFC Asset Management Company Ltd.", "HDFC Asset Management Company Ltd."),
                         ("HDFC Bank Ltd.", "HDFC Bank Ltd."),
                         ("HDFC Life Insurance Company Ltd.", "HDFC Life Insurance Company Ltd."),
                         ("HFCL Ltd.", "HFCL Ltd."),
                         ("Happiest Minds Technologies Ltd.", "Happiest Minds Technologies Ltd."),
                         ("Hatsun Agro Product Ltd.", "Hatsun Agro Product Ltd."),
                         ("Havells India Ltd.", "Havells India Ltd."),
                         ("HeidelbergCement India Ltd.", "HeidelbergCement India Ltd."),
                         ("Hemisphere Properties India Ltd.", "Hemisphere Properties India Ltd."),
                         ("Hero MotoCorp Ltd.", "Hero MotoCorp Ltd."),
                         ("Himadri Speciality Chemical Ltd.", "Himadri Speciality Chemical Ltd."),
                         ("Hindalco Industries Ltd.", "Hindalco Industries Ltd."),
                         ("Hindustan Aeronautics Ltd.", "Hindustan Aeronautics Ltd."),
                         ("Hindustan Copper Ltd.", "Hindustan Copper Ltd."),
                         ("Hindustan Petroleum Corporation Ltd.", "Hindustan Petroleum Corporation Ltd."),
                         ("Hindustan Unilever Ltd.", "Hindustan Unilever Ltd."),
                         ("Hindustan Zinc Ltd.", "Hindustan Zinc Ltd."),
                         ("Honeywell Automation India Ltd.", "Honeywell Automation India Ltd."),
                         ("Housing & Urban Development Corporation Ltd.",
                          "Housing & Urban Development Corporation Ltd."),
                         ("Housing Development Finance Corporation Ltd.",
                          "Housing Development Finance Corporation Ltd."),
                         ("Huhtamaki India Ltd.", "Huhtamaki India Ltd."),
                         ("ICICI Bank Ltd.", "ICICI Bank Ltd."),
                         ("ICICI Lombard General Insurance Company Ltd.",
                          "ICICI Lombard General Insurance Company Ltd."),
                         ("ICICI Prudential Life Insurance Company Ltd.",
                          "ICICI Prudential Life Insurance Company Ltd."),
                         ("ICICI Securities Ltd.", "ICICI Securities Ltd."),
                         ("IDBI Bank Ltd.", "IDBI Bank Ltd."),
                         ("IDFC First Bank Ltd.", "IDFC First Bank Ltd."),
                         ("IDFC Ltd.", "IDFC Ltd."),
                         ("IFB Industries Ltd.", "IFB Industries Ltd."),
                         ("IIFL Finance Ltd.", "IIFL Finance Ltd."),
                         ("IIFL Wealth Management Ltd.", "IIFL Wealth Management Ltd."),
                         ("IOL Chem and Pharma Ltd.", "IOL Chem and Pharma Ltd."),
                         ("IRB Infrastructure Developers Ltd.", "IRB Infrastructure Developers Ltd."),
                         ("IRCON International Ltd.", "IRCON International Ltd."),
                         ("ITC Ltd.", "ITC Ltd."),
                         ("ITI Ltd.", "ITI Ltd."),
                         ("India Cements Ltd.", "India Cements Ltd."),
                         ("Indiabulls Housing Finance Ltd.", "Indiabulls Housing Finance Ltd."),
                         ("Indiabulls Real Estate Ltd.", "Indiabulls Real Estate Ltd."),
                         ("Indiamart Intermesh Ltd.", "Indiamart Intermesh Ltd."),
                         ("Indian Bank", "Indian Bank"),
                         ("Indian Energy Exchange Ltd.", "Indian Energy Exchange Ltd."),
                         ("Indian Hotels Co. Ltd.", "Indian Hotels Co. Ltd."),
                         ("Indian Oil Corporation Ltd.", "Indian Oil Corporation Ltd."),
                         ("Indian Overseas Bank", "Indian Overseas Bank"),
                         ("Indian Railway Catering And Tourism Corporation Ltd.",
                          "Indian Railway Catering And Tourism Corporation Ltd."),
                         ("Indo Count Industries Ltd.", "Indo Count Industries Ltd."),
                         ("Indoco Remedies Ltd.", "Indoco Remedies Ltd."),
                         ("Indraprastha Gas Ltd.", "Indraprastha Gas Ltd."),
                         ("Indus Towers Ltd.", "Indus Towers Ltd."),
                         ("IndusInd Bank Ltd.", "IndusInd Bank Ltd."),
                         ("Infibeam Avenues Ltd.", "Infibeam Avenues Ltd."),
                         ("Info Edge (India) Ltd.", "Info Edge (India) Ltd."),
                         ("Infosys Ltd.", "Infosys Ltd."),
                         ("Ingersoll Rand (India) Ltd.", "Ingersoll Rand (India) Ltd."),
                         ("Inox Leisure Ltd.", "Inox Leisure Ltd."),
                         ("Intellect Design Arena Ltd.", "Intellect Design Arena Ltd."),
                         ("InterGlobe Aviation Ltd.", "InterGlobe Aviation Ltd."),
                         ("Ipca Laboratories Ltd.", "Ipca Laboratories Ltd."),
                         ("J.B. Chemicals & Pharmaceuticals Ltd.", "J.B. Chemicals & Pharmaceuticals Ltd."),
                         ("J.K. Cement Ltd.", "J.K. Cement Ltd."),
                         ("JK Lakshmi Cement Ltd.", "JK Lakshmi Cement Ltd."),
                         ("JK Paper Ltd.", "JK Paper Ltd."),
                         ("JK Tyre & Industries Ltd.", "JK Tyre & Industries Ltd."),
                         ("JM Financial Ltd.", "JM Financial Ltd."),
                         ("JSW Energy Ltd.", "JSW Energy Ltd."),
                         ("JSW Steel Ltd.", "JSW Steel Ltd."),
                         ("JTEKT India Ltd.", "JTEKT India Ltd."),
                         ("Jamna Auto Industries Ltd.", "Jamna Auto Industries Ltd."),
                         ("Jindal Saw Ltd.", "Jindal Saw Ltd."),
                         ("Jindal Stainless (Hisar) Ltd.", "Jindal Stainless (Hisar) Ltd."),
                         ("Jindal Stainless Ltd.", "Jindal Stainless Ltd."),
                         ("Jindal Steel & Power Ltd.", "Jindal Steel & Power Ltd."),
                         ("Johnson Controls - Hitachi Air Conditioning India Ltd.",
                          "Johnson Controls - Hitachi Air Conditioning India Ltd."),
                         ("Jubilant Foodworks Ltd.", "Jubilant Foodworks Ltd."),
                         ("Justdial Ltd.", "Justdial Ltd."),
                         ("Jyothy Labs Ltd.", "Jyothy Labs Ltd."),
                         ("K.P.R. Mill Ltd.", "K.P.R. Mill Ltd."),
                         ("KEI Industries Ltd.", "KEI Industries Ltd."),
                         ("KNR Constructions Ltd.", "KNR Constructions Ltd."),
                         ("KPIT Technologies Ltd.", "KPIT Technologies Ltd."),
                         ("KRBL Ltd.", "KRBL Ltd."),
                         ("KSB Ltd.", "KSB Ltd."),
                         ("Kajaria Ceramics Ltd.", "Kajaria Ceramics Ltd."),
                         ("Kalpataru Power Transmission Ltd.", "Kalpataru Power Transmission Ltd."),
                         ("Kansai Nerolac Paints Ltd.", "Kansai Nerolac Paints Ltd."),
                         ("Karur Vysya Bank Ltd.", "Karur Vysya Bank Ltd."),
                         ("Kaveri Seed Company Ltd.", "Kaveri Seed Company Ltd."),
                         ("Kec International Ltd.", "Kec International Ltd."),
                         ("Kotak Mahindra Bank Ltd.", "Kotak Mahindra Bank Ltd."),
                         ("L&T Finance Holdings Ltd.", "L&T Finance Holdings Ltd."),
                         ("L&T Technology Services Ltd.", "L&T Technology Services Ltd."),
                         ("LIC Housing Finance Ltd.", "LIC Housing Finance Ltd."),
                         ("La Opala RG Ltd.", "La Opala RG Ltd."),
                         ("Lakshmi Machine Works Ltd.", "Lakshmi Machine Works Ltd."),
                         ("Larsen & Toubro Infotech Ltd.", "Larsen & Toubro Infotech Ltd."),
                         ("Larsen & Toubro Ltd.", "Larsen & Toubro Ltd."),
                         ("Laurus Labs Ltd.", "Laurus Labs Ltd."),
                         ("Lemon Tree Hotels Ltd.", "Lemon Tree Hotels Ltd."),
                         ("Linde India Ltd.", "Linde India Ltd."),
                         ("Lupin Ltd.", "Lupin Ltd."),
                         ("Lux Industries Ltd.", "Lux Industries Ltd."),
                         ("MAS Financial Services Ltd.", "MAS Financial Services Ltd."),
                         ("MMTC Ltd.", "MMTC Ltd."),
                         ("MOIL Ltd.", "MOIL Ltd."),
                         ("MRF Ltd.", "MRF Ltd."),
                         ("Mahanagar Gas Ltd.", "Mahanagar Gas Ltd."),
                         ("Maharashtra Scooters Ltd.", "Maharashtra Scooters Ltd."),
                         ("Maharashtra Seamless Ltd.", "Maharashtra Seamless Ltd."),
                         ("Mahindra & Mahindra Financial Services Ltd.", "Mahindra & Mahindra Financial Services Ltd."),
                         ("Mahindra & Mahindra Ltd.", "Mahindra & Mahindra Ltd."),
                         ("Mahindra CIE Automotive Ltd.", "Mahindra CIE Automotive Ltd."),
                         ("Mahindra Holidays & Resorts India Ltd.", "Mahindra Holidays & Resorts India Ltd."),
                         ("Mahindra Logistics Ltd.", "Mahindra Logistics Ltd."),
                         ("Manappuram Finance Ltd.", "Manappuram Finance Ltd."),
                         ("Mangalore Refinery & Petrochemicals Ltd.", "Mangalore Refinery & Petrochemicals Ltd."),
                         ("Marico Ltd.", "Marico Ltd."),
                         ("Maruti Suzuki India Ltd.", "Maruti Suzuki India Ltd."),
                         ("Max Financial Services Ltd.", "Max Financial Services Ltd."),
                         ("Max Healthcare Institute Ltd.", "Max Healthcare Institute Ltd."),
                         ("Mazagoan Dock Shipbuilders Ltd.", "Mazagoan Dock Shipbuilders Ltd."),
                         ("Metropolis Healthcare Ltd.", "Metropolis Healthcare Ltd."),
                         ("MindTree Ltd.", "MindTree Ltd."),
                         ("Minda Corporation Ltd.", "Minda Corporation Ltd."),
                         ("Minda Industries Ltd.", "Minda Industries Ltd."),
                         ("Mishra Dhatu Nigam Ltd.", "Mishra Dhatu Nigam Ltd."),
                         ("Motherson Sumi Systems Ltd.", "Motherson Sumi Systems Ltd."),
                         ("Motilal Oswal Financial Services Ltd.", "Motilal Oswal Financial Services Ltd."),
                         ("MphasiS Ltd.", "MphasiS Ltd."),
                         ("Multi Commodity Exchange of India Ltd.", "Multi Commodity Exchange of India Ltd."),
                         ("Muthoot Finance Ltd.", "Muthoot Finance Ltd."),
                         ("NATCO Pharma Ltd.", "NATCO Pharma Ltd."),
                         ("NBCC (India) Ltd.", "NBCC (India) Ltd."),
                         ("NCC Ltd.", "NCC Ltd."),
                         ("NESCO Ltd.", "NESCO Ltd."),
                         ("NHPC Ltd.", "NHPC Ltd."),
                         ("NLC India Ltd.", "NLC India Ltd."),
                         ("NMDC Ltd.", "NMDC Ltd."),
                         ("NOCIL Ltd.", "NOCIL Ltd."),
                         ("NTPC Ltd.", "NTPC Ltd."),
                         ("Narayana Hrudayalaya Ltd.", "Narayana Hrudayalaya Ltd."),
                         ("National Aluminium Co. Ltd.", "National Aluminium Co. Ltd."),
                         ("National Fertilizers Ltd.", "National Fertilizers Ltd."),
                         ("Navin Fluorine International Ltd.", "Navin Fluorine International Ltd."),
                         ("Nestle India Ltd.", "Nestle India Ltd."),
                         ("Network18 Media & Investments Ltd.", "Network18 Media & Investments Ltd."),
                         ("Nilkamal Ltd.", "Nilkamal Ltd."),
                         ("Nippon Life India Asset Management Ltd.", "Nippon Life India Asset Management Ltd."),
                         ("Oberoi Realty Ltd.", "Oberoi Realty Ltd."),
                         ("Oil & Natural Gas Corporation Ltd.", "Oil & Natural Gas Corporation Ltd."),
                         ("Oil India Ltd.", "Oil India Ltd."),
                         ("Oracle Financial Services Software Ltd.", "Oracle Financial Services Software Ltd."),
                         ("Orient Electric Ltd.", "Orient Electric Ltd."),
                         ("Orient Refractories Ltd.", "Orient Refractories Ltd."),
                         ("PI Industries Ltd.", "PI Industries Ltd."),
                         ("PNB Housing Finance Ltd.", "PNB Housing Finance Ltd."),
                         ("PNC Infratech Ltd.", "PNC Infratech Ltd."),
                         ("PVR Ltd.", "PVR Ltd."),
                         ("Page Industries Ltd.", "Page Industries Ltd."),
                         ("Persistent Systems Ltd.", "Persistent Systems Ltd."),
                         ("Petronet LNG Ltd.", "Petronet LNG Ltd."),
                         ("Pfizer Ltd.", "Pfizer Ltd."),
                         ("Phillips Carbon Black Ltd.", "Phillips Carbon Black Ltd."),
                         ("Phoenix Mills Ltd.", "Phoenix Mills Ltd."),
                         ("Pidilite Industries Ltd.", "Pidilite Industries Ltd."),
                         ("Piramal Enterprises Ltd.", "Piramal Enterprises Ltd."),
                         ("Poly Medicure Ltd.", "Poly Medicure Ltd."),
                         ("Polycab India Ltd.", "Polycab India Ltd."),
                         ("Polyplex Corporation Ltd.", "Polyplex Corporation Ltd."),
                         ("Power Finance Corporation Ltd.", "Power Finance Corporation Ltd."),
                         ("Power Grid Corporation of India Ltd.", "Power Grid Corporation of India Ltd."),
                         ("Prestige Estates Projects Ltd.", "Prestige Estates Projects Ltd."),
                         ("Prince Pipes and Fittings Ltd.", "Prince Pipes and Fittings Ltd."),
                         ("Prism Johnson Ltd.", "Prism Johnson Ltd."),
                         ("Procter & Gamble Health Ltd.", "Procter & Gamble Health Ltd."),
                         ("Procter & Gamble Hygiene & Health Care Ltd.", "Procter & Gamble Hygiene & Health Care Ltd."),
                         ("Punjab National Bank", "Punjab National Bank"),
                         ("Quess Corp Ltd.", "Quess Corp Ltd."),
                         ("RBL Bank Ltd.", "RBL Bank Ltd."),
                         ("REC Ltd.", "REC Ltd."),
                         ("RITES Ltd.", "RITES Ltd."),
                         ("Radico Khaitan Ltd", "Radico Khaitan Ltd"),
                         ("Rail Vikas Nigam Ltd.", "Rail Vikas Nigam Ltd."),
                         ("Rain Industries Ltd", "Rain Industries Ltd"),
                         ("Rajesh Exports Ltd.", "Rajesh Exports Ltd."),
                         ("Rallis India Ltd.", "Rallis India Ltd."),
                         ("Rashtriya Chemicals & Fertilizers Ltd.", "Rashtriya Chemicals & Fertilizers Ltd."),
                         ("Ratnamani Metals & Tubes Ltd.", "Ratnamani Metals & Tubes Ltd."),
                         ("Raymond Ltd.", "Raymond Ltd."),
                         ("Redington (India) Ltd.", "Redington (India) Ltd."),
                         ("Relaxo Footwears Ltd.", "Relaxo Footwears Ltd."),
                         ("Reliance Industries Ltd.", "Reliance Industries Ltd."),
                         ("Responsive Industries Ltd.", "Responsive Industries Ltd."),
                         ("Rossari Biotech Ltd.", "Rossari Biotech Ltd."),
                         ("Route Mobile Ltd.", "Route Mobile Ltd."),
                         ("SBI Cards and Payment Services Ltd.", "SBI Cards and Payment Services Ltd."),
                         ("SBI Life Insurance Company Ltd.", "SBI Life Insurance Company Ltd."),
                         ("SIS Ltd.", "SIS Ltd."),
                         ("SJVN Ltd.", "SJVN Ltd."),
                         ("SKF India Ltd.", "SKF India Ltd."),
                         ("SRF Ltd.", "SRF Ltd."),
                         ("Sanofi India Ltd.", "Sanofi India Ltd."),
                         ("Schaeffler India Ltd.", "Schaeffler India Ltd."),
                         ("Schneider Electric Infrastructure Ltd.", "Schneider Electric Infrastructure Ltd."),
                         ("Sequent Scientific Ltd.", "Sequent Scientific Ltd."),
                         ("Sharda Cropchem Ltd.", "Sharda Cropchem Ltd."),
                         ("Sheela Foam Ltd.", "Sheela Foam Ltd."),
                         ("Shilpa Medicare Ltd.", "Shilpa Medicare Ltd."),
                         ("Shipping Corporation of India Ltd.", "Shipping Corporation of India Ltd."),
                         ("Shoppers Stop Ltd.", "Shoppers Stop Ltd."),
                         ("Shree Cement Ltd.", "Shree Cement Ltd."),
                         ("Shriram City Union Finance Ltd.", "Shriram City Union Finance Ltd."),
                         ("Shriram Transport Finance Co. Ltd.", "Shriram Transport Finance Co. Ltd."),
                         ("Siemens Ltd.", "Siemens Ltd."),
                         ("Sobha Ltd.", "Sobha Ltd."),
                         ("Solar Industries India Ltd.", "Solar Industries India Ltd."),
                         ("Solara Active Pharma Sciences Ltd.", "Solara Active Pharma Sciences Ltd."),
                         ("Sonata Software Ltd.", "Sonata Software Ltd."),
                         ("Spandana Sphoorty Financial Ltd.", "Spandana Sphoorty Financial Ltd."),
                         ("Spicejet Ltd.", "Spicejet Ltd."),
                         ("Star Cement Ltd.", "Star Cement Ltd."),
                         ("State Bank of India", "State Bank of India"),
                         ("Steel Authority of India Ltd.", "Steel Authority of India Ltd."),
                         ("Sterling And Wilson Solar Ltd.", "Sterling And Wilson Solar Ltd."),
                         ("Sterlite Technologies Ltd.", "Sterlite Technologies Ltd."),
                         ("Strides Pharma Science Ltd.", "Strides Pharma Science Ltd."),
                         ("Sudarshan Chemical Industries Ltd.", "Sudarshan Chemical Industries Ltd."),
                         ("Sumitomo Chemical India Ltd.", "Sumitomo Chemical India Ltd."),
                         ("Sun Pharma Advanced Research Company Ltd.", "Sun Pharma Advanced Research Company Ltd."),
                         ("Sun Pharmaceutical Industries Ltd.", "Sun Pharmaceutical Industries Ltd."),
                         ("Sun TV Network Ltd.", "Sun TV Network Ltd."),
                         ("Sundaram Clayton Ltd.", "Sundaram Clayton Ltd."),
                         ("Sundaram Finance Ltd.", "Sundaram Finance Ltd."),
                         ("Sundram Fasteners Ltd.", "Sundram Fasteners Ltd."),
                         ("Sunteck Realty Ltd.", "Sunteck Realty Ltd."),
                         ("Suprajit Engineering Ltd.", "Suprajit Engineering Ltd."),
                         ("Supreme Industries Ltd.", "Supreme Industries Ltd."),
                         ("Supreme Petrochem Ltd.", "Supreme Petrochem Ltd."),
                         ("Suven Pharmaceuticals Ltd.", "Suven Pharmaceuticals Ltd."),
                         ("Suzlon Energy Ltd.", "Suzlon Energy Ltd."),
                         ("Swan Energy Ltd.", "Swan Energy Ltd."),
                         ("Symphony Ltd.", "Symphony Ltd."),
                         ("Syngene International Ltd.", "Syngene International Ltd."),
                         ("TCI Express Ltd.", "TCI Express Ltd."),
                         ("TCNS Clothing Co. Ltd.", "TCNS Clothing Co. Ltd."),
                         ("TTK Prestige Ltd.", "TTK Prestige Ltd."),
                         ("TV18 Broadcast Ltd.", "TV18 Broadcast Ltd."),
                         ("TVS Motor Company Ltd.", "TVS Motor Company Ltd."),
                         ("Tanla Platforms Ltd.", "Tanla Platforms Ltd."),
                         ("Tasty Bite Eatables Ltd.", "Tasty Bite Eatables Ltd."),
                         ("Tata Chemicals Ltd.", "Tata Chemicals Ltd."),
                         ("Tata Coffee Ltd.", "Tata Coffee Ltd."),
                         ("Tata Communications Ltd.", "Tata Communications Ltd."),
                         ("Tata Consultancy Services Ltd.", "Tata Consultancy Services Ltd."),
                         ("Tata Consumer Products Ltd.", "Tata Consumer Products Ltd."),
                         ("Tata Elxsi Ltd.", "Tata Elxsi Ltd."),
                         ("Tata Investment Corporation Ltd.", "Tata Investment Corporation Ltd."),
                         ("Tata Motors Ltd DVR", "Tata Motors Ltd DVR"),
                         ("Tata Motors Ltd.", "Tata Motors Ltd."),
                         ("Tata Power Co. Ltd.", "Tata Power Co. Ltd."),
                         ("Tata Steel Ltd.", "Tata Steel Ltd."),
                         ("Teamlease Services Ltd.", "Teamlease Services Ltd."),
                         ("Tech Mahindra Ltd.", "Tech Mahindra Ltd."),
                         ("The New India Assurance Company Ltd.", "The New India Assurance Company Ltd."),
                         ("The Ramco Cements Ltd.", "The Ramco Cements Ltd."),
                         ("Thermax Ltd.", "Thermax Ltd."),
                         ("Thyrocare Technologies Ltd.", "Thyrocare Technologies Ltd."),
                         ("Timken India Ltd.", "Timken India Ltd."),
                         ("Titan Company Ltd.", "Titan Company Ltd."),
                         ("Torrent Pharmaceuticals Ltd.", "Torrent Pharmaceuticals Ltd."),
                         ("Torrent Power Ltd.", "Torrent Power Ltd."),
                         ("Trent Ltd.", "Trent Ltd."),
                         ("Trident Ltd.", "Trident Ltd."),
                         ("Triveni Turbine Ltd.", "Triveni Turbine Ltd."),
                         ("Tube Investments of India Ltd.", "Tube Investments of India Ltd."),
                         ("UCO Bank", "UCO Bank"),
                         ("UFLEX Ltd.", "UFLEX Ltd."),
                         ("UPL Ltd.", "UPL Ltd."),
                         ("UTI Asset Management Company Ltd.", "UTI Asset Management Company Ltd."),
                         ("Ujjivan Financial Services Ltd.", "Ujjivan Financial Services Ltd."),
                         ("Ujjivan Small Finance Bank Ltd.", "Ujjivan Small Finance Bank Ltd."),
                         ("UltraTech Cement Ltd.", "UltraTech Cement Ltd."),
                         ("Union Bank of India", "Union Bank of India"),
                         ("United Breweries Ltd.", "United Breweries Ltd."),
                         ("United Spirits Ltd.", "United Spirits Ltd."),
                         ("V-Guard Industries Ltd.", "V-Guard Industries Ltd."),
                         ("V-Mart Retail Ltd.", "V-Mart Retail Ltd."),
                         ("V.I.P. Industries Ltd.", "V.I.P. Industries Ltd."),
                         ("VST Industries Ltd.", "VST Industries Ltd."),
                         ("Vaibhav Global Ltd.", "Vaibhav Global Ltd."),
                         ("Vakrangee Ltd.", "Vakrangee Ltd."),
                         ("Valiant Organics Ltd.", "Valiant Organics Ltd."),
                         ("Vardhman Textiles Ltd.", "Vardhman Textiles Ltd."),
                         ("Varroc Engineering Ltd.", "Varroc Engineering Ltd."),
                         ("Varun Beverages Ltd.", "Varun Beverages Ltd."),
                         ("Vedanta Ltd.", "Vedanta Ltd."),
                         ("Venky's (India) Ltd.", "Venky's (India) Ltd."),
                         ("Vinati Organics Ltd.", "Vinati Organics Ltd."),
                         ("Vodafone Idea Ltd.", "Vodafone Idea Ltd."),
                         ("Voltas Ltd.", "Voltas Ltd."),
                         ("WABCO India Ltd.", "WABCO India Ltd."),
                         ("Welspun Corp Ltd.", "Welspun Corp Ltd."),
                         ("Welspun India Ltd.", "Welspun India Ltd."),
                         ("Westlife Development Ltd.", "Westlife Development Ltd."),
                         ("Whirlpool of India Ltd.", "Whirlpool of India Ltd."),
                         ("Wipro Ltd.", "Wipro Ltd."),
                         ("Wockhardt Ltd.", "Wockhardt Ltd."),
                         ("Yes Bank Ltd.", "Yes Bank Ltd."),
                         ("Zee Entertainment Enterprises Ltd.", "Zee Entertainment Enterprises Ltd."),
                         ("Zensar Technolgies Ltd.", "Zensar Technolgies Ltd."),
                         ("Zydus Wellness Ltd.", "Zydus Wellness Ltd."),
                         ("eClerx Services Ltd.", "eClerx Services Ltd.")]
    STRATEGY = [
        ('44MA', '44MA'),
        ('50MA+LBB', '50MA+LBB'),
        ('50MA+UBB', '50MA+UBB'),
        ('SUPER-T+CCI', 'SUPER-T+CCI'),
        ('OTHER', 'OTHER'),
        ('FIBONACCI', 'FIBONACCI')
    ]
    EMOTIONS = [
        ('NORMAL', 'NORMAL'),
        ('BALANCE', 'BALANCE'),
        ('HAPPY', 'HAPPY'),
    ]
    TRADE_TYPE = [
        ('INTRADAY', 'INTRADAY'),
        ('SWING', 'SWING'),
        ('POSITIONAL', 'POSITIONAL')
    ]
    MISTAKES = [
        ('WRONG_PREDICTION', 'WRONG_PREDICTION'),
        ('SYSTEMLESS_TRADE', 'SYSTEMLESS_TRADE'),
        ('NONE', 'NONE')
    ]
    user = models.CharField(max_length=20, default='user')
    portfolio = models.FloatField(default=0.0)
    stock = models.CharField(choices=NIFTY_BETA_STOCKS, max_length=100,default='OTHER')
    stock_type = models.CharField(choices=TRADE_TYPE, max_length=10, default='SWING')
    buy_date = models.DateField(default=timezone.now)
    strategy = models.CharField(choices=STRATEGY, max_length=20, default='50MA+UBB')
    entry = models.FloatField(default=0.0)
    stoploss = models.FloatField(default=0.0)
    target = models.FloatField(default=0.0)
    quantity = models.FloatField(default=0.0)
    exit = models.FloatField(default=0.0)
    profit_loss_per_stock = models.FloatField(default=0.0)
    profile = models.FloatField(default=0.0)
    emotion = models.CharField(max_length=10, choices=EMOTIONS, default='NORMAL')
    mistake = models.CharField(max_length=20, choices=MISTAKES, default='NONE')
    graph = models.ImageField(upload_to='graph', blank=True)

    def __str__(self):
        return self.stock

    def get_img(self):
        return self.graph.url
