# Generated by Django 3.2.2 on 2021-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderecord', '0002_stockrecords_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecords',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
