# Generated by Django 3.2.2 on 2021-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderecord', '0003_alter_stockrecords_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecords',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
