# Generated by Django 3.2.2 on 2021-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderecord', '0005_alter_stockrecords_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecords',
            name='graph',
            field=models.ImageField(blank=True, default='menu.png', upload_to='graph'),
        ),
    ]
