# Generated by Django 3.2.2 on 2021-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderecord', '0008_alter_stockrecords_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecords',
            name='user',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
